name: Tests

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

defaults:
  run:
    shell: bash

jobs:
  Pytest:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg
    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-tests.txt
            requirements-optional.txt

      - name: Install rocketpy + test deps
        run: |
          pip install .[all]
          pip install -r requirements-tests.txt

      - name: Test importing rocketpy
        run: python -c "import sys, rocketpy; print(f'{rocketpy.__name__} running on Python {sys.version}')"

      - name: Run unit tests
        run: pytest tests/unit

      - name: Run integration tests
        run: pytest tests/integration
